# .github/workflows/http_status.yml
name: Auto HTTP Status – cleaned_data/*.csv (manual only)

on:
  workflow_dispatch:
    inputs:
      csv_file:
        description: "CSV file in cleaned_data/ (leave empty = process all)"
        required: false
        default: ""

env:
  FLARE_ENDPOINT: http://localhost:8191/v1

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set
        run: |
          if [ -z "${{ github.event.inputs.csv_file }}" ]; then
            files=(cleaned_data/*.csv)
          else
            files=("cleaned_data/${{ github.event.inputs.csv_file }}")
          fi

          # Build JSON array of simple strings
          json=$(printf '%s\n' "${files[@]}" | jq -R . | jq -s .)
          echo "matrix=$json" >> $GITHUB_OUTPUT

  scrape:
    needs: discover
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.discover.outputs.matrix) }}
    services:
      flaresolverr:
        image: flaresolverr/flaresolverr
        ports:
          - 8191:8191

    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install cloudscraper pandas aiohttp tqdm
      - run: |
          mkdir -p http_status
          python http_status_finder.py --input-file "${{ matrix.file }}" --output-dir http_status
      - run: |
          git config user.name  "Ifeoluwa Oseni"
          git config user.email "ifeoseni@gmail.com"
          git add "http_status/$(basename '${{ matrix.file }}')"
          git diff --cached --quiet || {
            git commit -m "chore: update http_status/$(basename '${{ matrix.file }}')"
            git push origin HEAD:${{ github.ref }}
          }
